services:
  yolonet_afm:
    build: .
    stdin_open: true
    container_name: YOLOnet-AFM
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - data:/app/data
      - models:/app/models
    environment:
      - DISPLAY=:1.0
      - PYTHONUNBUFFERED=1
    tty: true

volumes:
  data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./data
      o: bind
  models:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./models
      o: bind

