services:
  yolonet_afm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["tail", "-f", "/dev/null"]

    stdin_open: true
    container_name: YOLOnet-AFM
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=:1.0
      - PYTHONUNBUFFERED=1
    tty: true
